#!/usr/bin/env bash

echo "Welcome to the basic calculator!" | tee operation_history.txt
echo "Enter an arithmetic operation or type 'quit' to quit:" | tee -a operation_history.txt
read input
echo "$input" >> operation_history.txt
re='^[-]?[0-9]*[.]?[0-9]+[ ]?[-\/*+^][ ]?[-]?[0-9]*[.]?[0-9]+$'
while [[ $input != 'quit' ]]
do
if [[ "$input" =~ $re ]]; then
    echo $(echo "scale=2; $input" | bc -l) | tee -a operation_history.txt
    echo "Enter an arithmetic operation or type 'quit' to quit:" | tee -a operation_history.txt
    read input
    echo "$input" >> operation_history.txt
else
    echo "Operation check failed!" | tee -a operation_history.txt
    echo "Enter an arithmetic operation or type 'quit' to quit:" | tee -a operation_history.txt
    read input
    echo "$input" >> operation_history.txt
fi
done
echo "Goodbye!" | tee -a operation_history.txt
